train:
  _target_: src.datasets.CustomDatasetWav
  wavs_dir: /Users/andrewut/Downloads/LJSpeech-1.1/wavs
  limit: 2
  # part: "train-clean-100"
  # instance_transforms: ${transforms.instance_transforms.train}
# val:
#   _target_: src.datasets.LibrispeechDataset
#   part: "dev-clean"
#   instance_transforms: ${transforms.instance_transforms.inference}
# test:
#   _target_: src.datasets.LibrispeechDataset
#   part: "test-clean"
#   instance_transforms: ${transforms.instance_transforms.inference}
