train:
  _target_: src.datasets.CustomDatasetWav
  wavs_dir: /home/andrewut/dla/hw3/LJSpeech-1.1/wavs
  part: train
val:
  _target_: src.datasets.CustomDatasetWav
  wavs_dir: /home/andrewut/dla/hw3/LJSpeech-1.1/val
  part: val
