defaults:
  - generator: generator
  - metrics: example
  - datasets: synthesize_from_text # we do not want to run inference on training data
  - dataloader: example
  - transforms: example_only_instance
  - _self_
inferencer:
  device_tensors: ["spectrogram"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "/Users/andrewut/Downloads/model_best.pth" # path to the pretrained model
  text: null
