_target_: src.model.Generator
kernel_sizes:
  - 16
  - 16
  - 4
  - 4
dims:
  - 512
  - 256
  - 128
  - 64
dilations:
  - 1
  - 3
  - 5
mrf_kernel_sizes:
  - 3
  - 7
  - 11
paddings:
  - 4
  - 4
  - 1
  - 1